# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_auto_20170523_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
